ansible_user: kevin
build_base_path: "/home/{{ ansible_user }}"
git_dir: "{{ build_base_path }}/{{ application }}"
drupal_template_dir: "{{ build_base_path }}/{{ current_app }}/templates/"
application: ansible
env: "{{ custom_fields.dev_or_prod }}"
ceph_target_dir: /var/www/html/sites/default/files