ansible_user: kevin
build_base_path: "/home/{{ ansible_user }}/"
git_dir: "{{ build_base_path }}/{{ application }}"
drupal_template_dir: "{{ build_base_path }}/{{ current_app }}/playbook/templates/"
netbox_dns: netbox.thejfk.ca
interface: eth0
application: ansible
php_packages:
  - php
  - php-gd
  - php-pdo
  - php-mysql
  - php-dom
  - php-mbstring
  - php-curl
system_packages:
  - apache2
  - mysql-client
  - ncdu
  - gh
  - vim
  - nfs-common
  - htop
  - qemu-guest-agent
  - ceph-common