ansible_user: kevin
build_base_path: "/home/{{ ansible_user }}"
git_dir: "{{ build_base_path }}/{{ application }}"
drupal_template_dir: "{{ build_base_path }}/{{ current_app }}/templates/"
netbox_dns: netbox.thejfk.ca
application: ansible
php_packages:
  - php
  - php-gd
  - php-pdo
  - php-mysql
  - php-dom
  - php-mbstring
  - php-curl
system_packages:
  - apache2
  - mysql-client
  - ncdu
  - gh
  - vim
  - nfs-common
  - htop
  - qemu-guest-agent
  - ceph-common
nfs_target_dir: /home/{{ ansible_user }}/nfs-files
nfs_server: 192.168.11.20
nfs_share: /mnt/yes/gitbuilds/{{ current_app }}/files
dbName: "{{ current_app }}"
username: "{{ current_app }}"
drush: /var/www/vendor/drush/drush/drush
env: "{{ custom_fields.dev_or_prod }}"
nfs_options:
  - defaults
  - x-systemd.automount
  - x-systemd.idle-timeout=60s
  - soft
  - timeo=14
  - retrans=2
  - _netdev
ceph_monitors: "192.168.11.11:6789,192.168.11.12:6789,192.168.11.13:6789"
ceph_user: "admin"
ceph_target_dir: /var/www/html/sites/default/files