$ANSIBLE_VAULT;1.1;AES256
36383839643865393761653033646331623036373834366363636531333531613131363863613034
3764343735343137643934613939353735633130353465610a326366663631663864323263383737
30353134313332303038356236643539376635303265663261353330383630656161313861623230
6165656131636365650a386464643033316466643131303064363730376262616435633234326665
38353962626261353135643634663663613062653139306261336362623736376562646234656536
35393432646165306631373862323235393539323239666233636265303766393761373266336463
323763393136376565353433356233336239
