- name: My first play
  hosts: myhosts
  tasks:
    - name: Print repo variable
      ansible.builtin.debug:
        msg: "Repo variable for {{ inventory_hostname }} is {{ repo }}"
      vars:
        repo: "{{ hostvars[inventory_hostname]['repo'] }}"