- name: My first play
  hosts: myhosts
  tasks:
    - name: Print repo variable
            ansible.builtin.git:
        repo: "https://github.com/kevinabruner/{{ hostvars[inventory_hostname]['repo'] }}"
        dest: /home/kevin/gitpull
        update: yes