- name: Parallel Deploy for Dev
  hosts: role_drupal:&env_dev
  vars_files:
    - vars.yaml
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml
  pre_tasks:
    - name: Check build dir tasks from ansible 
      import_tasks: tasks/check-build-dir.yaml
  
  tasks:
    - name: Deploy dev tasks from ansible 
      import_tasks: tasks/2-deploy-dev.yaml