$ANSIBLE_VAULT;1.1;AES256
63333430353336383665353633373936346263663163663231393833323763373366656434396237
6565653661326532646132643061316235643139386465340a633938313431653133376665356136
63366239656332353235356437626366616137393134646139363162303732363264343435353338
3135366262333966310a633666343939643663373165383263323761313464346431306134643932
36643465626232356233393637303164613638323230633539313836323935333139636164373963
62663635646339373230326663356534613130663438656239396562663832373934623132653835
66373837386638353636643036626233663266626535303563376364666335656164626361386231
30303665313431313362383566376337656632316132376538386531353935346630663065623037
34613364363836353463346266326163336339356164633563373432323033656138643463343531
62613461643534666661303135333339363763633463663935336633616333313830373261333734
34366630383933363263396538393939343530383335396637663130626265373961636539313832
33386364386338323332316139663964376239643865373332666430303966633433616566633639
34326232373238656532663531323134646363353331643532376166353435303233646362613036
3338623731353030333637643235623261663131663237646133
