pivars:
  GITHUB_ACCESS_TOKEN: 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
  KEY_TITLE: pi
  priv_key_path: /home/kevin/.ssh/id_rsa
  pub_key_path: /home/kevin/.ssh/id_rsa.pub
  GIT_REPO: git@github.com:kevinabruner/pi.git
  GIT_BRANCH: main
  CLONE_DEST: /home/kevin/pi
  KNOWN_HOSTS_PATH: /home/kevin/.ssh/known_hosts
  GIT_EXECUTABLE: /usr/bin/git
