ANSIBLE_USER: kevin
GITHUB_ACCESS_TOKEN: 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
priv_key_path: /home/{{ ANSIBLE_USER }}/.ssh/id_rsa
pub_key_path: /home/{{ ANSIBLE_USER }}/.ssh/id_rsa.pub
GIT_REPO: git@github.com:kevinabruner/pi.git
GIT_BRANCH: main
CLONE_DEST: /home/{{ ANSIBLE_USER }}/pi
KNOWN_HOSTS_PATH: /home/{{ ANSIBLE_USER }}/.ssh/known_hosts
PI_DIR: /etc/pihole
netbox_dns: netbox.thejfk.ca
internal_proxy: 192.168.11.30