pivars:
  GITHUB_ACCESS_TOKEN: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            38396130613661653436626662613839363064346566316265383132346432626530323239346330
            6531393132393538613866643536646564633436393633380a363437613033393535346435663233
            34353035646436383230616665663735376139613237316531353163353361663730666666663635
            6231353730656361610a396666633565623436386136373135353438623831376162383430333939
            31643437643639303739366432393434376635326231356138363437653462306165393537326136
            3030386331343635633565633162383464356639373966373065

  KEY_TITLE: pi
  KEY_PATH: /home/kevin/.ssh/id_rsa.git
  GIT_REPO: ssh://  git@github.com:kevinabruner/pi.git
  GIT_BRANCH: main
  CLONE_DEST: /home/kevin/pi
  KNOWN_HOSTS_PATH: /home/kevin/.ssh/known_hosts
  GIT_EXECUTABLE: /usr/bin/git